title: "Janaki Keerthi"
description: "Software Development Engineer"
theme: jekyll-theme-cayman
# plugins:
#   - jekyll-remote-theme
# url: "https://janakikeerthi277.github.io"
# author: Janaki Keerthi
# email: janaki.keerthi@gmail.com
# social_links:
#   linkedin: https://linkedin.com/in/janakikeerthi
#   github: https://github.com/janakikeerthi277
