title: "Janaki Keerthi's Portfolio"
description: "A portfolio of my projects, skills, and experience."
theme: jekyll-theme-midnight
url: "https://janakikeerthi277.github.io"
author: Janaki Keerthi
email: janaki.keerthi@gmail.com
social_links:
  linkedin: https://linkedin.com/in/janakikeerthi
  github: https://github.com/janakikeerthi277
